training: 
  epochs: 100

target:
  num_x: 10
  num_y: 2
  num_hidden_layers: 1
  hidden_dim: 100
  training:
    iterations: 20000
    batch_size: 8192
    lr: 0.00001

scm:
  num_causes: 2
  num_layers: 3
  layer_dim: 10
  p_dropout: 0.8
  allow_xy_overlap: True